In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import os

KeyboardInterrupt:

In [6]:
file_path = "../data/transformed_combined_data.csv"

In [7]:
# Leer el archivo tranformado
df = pd.read_csv(file_path, encoding="utf-8")

/var/folders/ky/ttgzd64n7_v1dy09tmrkhp7m0000gn/T/ipykernel_91964/3544650691.py:2: DtypeWarning: Columns (17,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding="latin1")

In [8]:
print("\nEncabezado del DataFrame:")
print(df.head())

Encabezado del DataFrame:
    Ano  ID_Estado          Estado  ID_DDR             DDR  ID_CADER  \
0  2016          1  Aguascalientes       1  Aguascalientes         1
1  2016          1  Aguascalientes       1  Aguascalientes         1
2  2016          1  Aguascalientes       1  Aguascalientes         1
3  2016          1  Aguascalientes       1  Aguascalientes         1
4  2016          1  Aguascalientes       1  Aguascalientes         1

            CADER  ID_Municipio       Municipio  ID_Ciclo  ... Unidad_Medida  \
0  Aguascalientes             1  Aguascalientes         1  ...      Tonelada
1  Aguascalientes             1  Aguascalientes         1  ...      Tonelada
2  Aguascalientes             1  Aguascalientes         1  ...      Tonelada
3  Aguascalientes             1  Aguascalientes         1  ...      Tonelada
4  Aguascalientes             1  Aguascalientes         2  ...      Tonelada

   ID_Cultivo                       Cultivo  Superficie_Sembrada  \
0     5490000      Avena forrajera en verde                765.0
1     5900000     Cebada forrajera en verde                 35.0
2     9090000  Triticale forrajero en verde                611.0
3    15050000             Pastos y praderas                692.0
4     5490000      Avena forrajera en verde                 28.0

  Superficie_Cosechada  Superficie_Siniestrada Produccion_Volumen Rendimiento  \
0                765.0                     0.0           20865.75       27.28
1                 35.0                     0.0              945.0       27.00
2                611.0                     0.0            20446.0       33.46
3                692.0                     0.0            34912.7       50.45
4                 28.0                     0.0              746.4       26.66

   Precio_Promedio  Valor_Produccion
0           595.45       12424510.84
1           570.00         538650.00
2           593.17       12127953.82
3           601.15       20987769.60
4           545.91         407467.22

[5 rows x 24 columns]

In [9]:
# Mostrar el número de líneas (filas) del DataFrame
print("\nNúmero de líneas en el DataFrame:", len(df))

Número de líneas en el DataFrame: 1433266

In [10]:
print("\nValores nulos por columna:")
for column in df.columns:
    null_count = df[column].isnull().sum()
    print(f"{column}: {null_count} valores nulos")

Valores nulos por columna:
Ano: 0 valores nulos
ID_Estado: 0 valores nulos
Estado: 0 valores nulos
ID_DDR: 0 valores nulos
DDR: 0 valores nulos
ID_CADER: 0 valores nulos
CADER: 0 valores nulos
ID_Municipio: 0 valores nulos
Municipio: 0 valores nulos
ID_Ciclo: 0 valores nulos
Ciclo_Producto: 0 valores nulos
ID_Modalidad: 0 valores nulos
Modalidad: 0 valores nulos
ID_Unidad_Medida: 0 valores nulos
Unidad_Medida: 0 valores nulos
ID_Cultivo: 0 valores nulos
Cultivo: 0 valores nulos
Superficie_Sembrada: 0 valores nulos
Superficie_Cosechada: 0 valores nulos
Superficie_Siniestrada: 0 valores nulos
Produccion_Volumen: 0 valores nulos
Rendimiento: 0 valores nulos
Precio_Promedio: 0 valores nulos
Valor_Produccion: 0 valores nulos

In [8]:
def load_and_print_info(url):
    try:
        # Intentar cargar el dataset con codificación UTF-8
        df = pd.read_csv(url, encoding='utf-8')
    except UnicodeDecodeError:
        # Si falla, intentar con codificación ISO-8859-1
        df = pd.read_csv(url, encoding='ISO-8859-1')

    # Imprimir los campos y sus tipos
    print(f"Información del dataset: {url}")
    print(df.dtypes)
    print("\n")

    return df

In [15]:
load_and_print_info(file_path)

/var/folders/ky/ttgzd64n7_v1dy09tmrkhp7m0000gn/T/ipykernel_91964/1069891444.py:4: DtypeWarning: Columns (17,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url, encoding='utf-8')

Información del dataset: ../data/transformed_combined_data.csv
Ano                         int64
ID_Estado                   int64
Estado                     object
ID_DDR                      int64
DDR                        object
ID_CADER                    int64
CADER                      object
ID_Municipio                int64
Municipio                  object
ID_Ciclo                    int64
Ciclo_Producto             object
ID_Modalidad                int64
Modalidad                  object
ID_Unidad_Medida            int64
Unidad_Medida              object
ID_Cultivo                  int64
Cultivo                    object
Superficie_Sembrada        object
Superficie_Cosechada      float64
Superficie_Siniestrada    float64
Produccion_Volumen         object
Rendimiento               float64
Precio_Promedio           float64
Valor_Produccion          float64
dtype: object

,Ano,ID_Estado,Estado,ID_DDR,DDR,ID_CADER,CADER,ID_Municipio,Municipio,ID_Ciclo,...,Unidad_Medida,ID_Cultivo,Cultivo,Superficie_Sembrada,Superficie_Cosechada,Superficie_Siniestrada,Produccion_Volumen,Rendimiento,Precio_Promedio,Valor_Produccion
0,2016,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,...,Tonelada,5490000,Avena forrajera en verde,765.0,765.0,0.0,20865.75,27.28,595.45,12424510.84
1,2016,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,...,Tonelada,5900000,Cebada forrajera en verde,35.0,35.0,0.0,945.0,27.00,570.00,538650.00
2,2016,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,...,Tonelada,9090000,Triticale forrajero en verde,611.0,611.0,0.0,20446.0,33.46,593.17,12127953.82
3,2016,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,...,Tonelada,15050000,Pastos y praderas,692.0,692.0,0.0,34912.7,50.45,601.15,20987769.60
4,2016,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,2,...,Tonelada,5490000,Avena forrajera en verde,28.0,28.0,0.0,746.4,26.66,545.91,407467.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1433261,2018,32,Zacatecas,190,Jalpa,4,Jalpa,19,Jalpa,3,...,Tonelada,9120000,Tuna,5.0,5.0,0.0,49.2,9.84,4690.00,230748.00
1433262,2018,32,Zacatecas,190,Jalpa,4,Jalpa,19,Jalpa,3,...,Tonelada,9130000,Uva,20.0,17.0,0.0,139.2,8.19,27999.99,3897598.61
1433263,2018,32,Zacatecas,190,Jalpa,4,Jalpa,19,Jalpa,3,...,Tonelada,15050000,Pastos y praderas,92.0,92.0,0.0,5532.33,60.13,590.33,3265909.55
1433264,2018,32,Zacatecas,190,Jalpa,4,Jalpa,19,Jalpa,3,...,Tonelada,5050000,Agave,23.0,7.0,0.0,681.66,97.38,18000.00,12269880.00
1433265,2018,32,Zacatecas,190,Jalpa,4,Jalpa,19,Jalpa,3,...,Tonelada,15050000,Pastos y praderas,1023.0,933.0,0.0,33124.76,35.50,582.34,19290010.93

In [ ]:
plt.style.use('custom_style')

# Carga del archivo CSV
def plot_graphs(file_path):
    df = pd.read_csv(file_path, encoding="utf-8")

    # Lista de gráficos a generar
    charts = [
        ("Cultivo", "Superficie_Sembrada", "Superficie Sembrada por Cultivo"),
        ("Cultivo", "Superficie_Cosechada", "Superficie Cosechada por Cultivo"),
        ("Cultivo", "Produccion_Volumen", "Volumen de Producción por Cultivo"),
        ("Cultivo", "Rendimiento", "Rendimiento por Cultivo"),
        ("Cultivo", "Precio_Promedio", "Precio Promedio por Cultivo"),
        ("Ano", "Superficie_Sembrada", "Superficie Sembrada por Año"),
        ("Ano", "Produccion_Volumen", "Volumen de Producción por Año"),
        ("Ano", "Rendimiento", "Rendimiento Promedio por Año"),
        ("Estado", "Superficie_Sembrada", "Superficie Sembrada por Estado"),
        ("Estado", "Valor_Produccion", "Valor de Producción por Estado"),
    ]

    # Convertir columnas numéricas si es necesario
    numeric_columns = ["Superficie_Sembrada", "Superficie_Cosechada", "Produccion_Volumen"]
    for col in numeric_columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Generar los gráficos usando los 10 valores mayores
    for x, y, title in charts:
        plt.figure(figsize=(10, 6))
        top_10 = df.groupby(x)[y].sum().nlargest(10)
        top_10.plot(kind="bar", title=title)
        plt.xlabel(x)
        plt.ylabel(y)
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

# Llamada a la función con el archivo CSV
file_path = "../data/transformed_combined_data.csv"  # Reemplaza con la ruta a tu archivo CSV
plot_graphs(file_path)

NameError: name 'pd' is not defined